(function(){
const TEXT=window.FDTK.TEXT,SCENARIO=window.FDTK.SCENARIO,fmt=window.FDTK.formatters,gameApi=window.FDTK.game,storageApi=window.FDTK.storage;
const S={
none:'\u65e0\u4e3b',
soundOn:'\u97f3\u6548\uff1a\u5f00',
soundOff:'\u97f3\u6548\uff1a\u5173',
enterFullscreen:'\u8fdb\u5165\u5168\u5c4f',
exitFullscreen:'\u9000\u51fa\u5168\u5c4f',
selectForceDesc:'\u9009\u62e9\u4e00\u4e2a\u52bf\u529b\u5f00\u5c40\u3002',
roleFallback:'\u4eba\u7269',
help:'\u5e2e\u52a9',
help1:'\u4e00\u7ea7\u83dc\u5355\u7528\u4e8e\u5207\u6362\u5185\u653f\u3001\u519b\u4e8b\u3001\u6b66\u5c06\u4e09\u7c7b\u4e8b\u52a1\u3002',
help2:'\u5c06\u9f20\u6807\u505c\u5728\u53c2\u6570\u6216\u6309\u94ae\u4e0a\uff0c\u53ef\u770b\u5177\u4f53\u8bf4\u660e\u3002',
help3:'\u53f3\u4e0b\u5c0f\u5730\u56fe\u8282\u70b9\u5747\u5df2\u6807\u51fa\u57ce\u5e02\u540d\u3002',
help4:'\u5f81\u7a0e\u548c\u5f81\u5175\u4f1a\u635f\u8017\u4eba\u53e3\u4e0e\u6c11\u5fc3\uff0c\u8fc7\u91cd\u5c06\u8bf1\u53d1\u53db\u4e71\u3002',
taxHintEnabled:'\u5f81\u7a0e\u4f1a\u589e\u52a0\u91d1\u94b1\uff0c\u4f46\u4f1a\u964d\u4f4e\u4eba\u53e3\u3001\u5fe0\u8bda\u4e0e\u6cbb\u5b89\u3002\u5f53\u524d\u7a0e\u8d1f ',
taxHintDisabled:'\u672c\u57ce\u6682\u4e0d\u5b9c\u5f81\u7a0e\uff1a\u4eba\u53e3 ',
taxHintMid:'\uff0c\u5fe0\u8bda ',
taxHintEnd:'\uff0c\u7a0e\u8d1f ',
recruitHintEnabled:'\u5f81\u5175\u4f1a\u63d0\u5347\u5175\u529b\uff0c\u4f46\u4f1a\u62bd\u8d70\u58ee\u4e01\uff0c\u964d\u4f4e\u4eba\u53e3\u3001\u5fe0\u8bda\u4e0e\u6cbb\u5b89\u3002\u5f53\u524d\u5175\u5f79 ',
recruitHintDisabled:'\u672c\u57ce\u6682\u4e0d\u5b9c\u5f81\u5175\uff1a\u4eba\u53e3 ',
recruitHintMid:'\uff0c\u5fe0\u8bda ',
recruitHintEnd:'\uff0c\u5175\u5f79 ',
farm:'\u519c\u7530',market:'\u5e02\u96c6',office:'\u5b98\u7f72',barracks:'\u5175\u8425',gate:'\u57ce\u95e8',ward:'\u8857\u574a',
population:'\u4eba\u53e3',development:'\u5f00\u53d1',loyalty:'\u5fe0\u8bda',troops:'\u5175\u529b',defense:'\u57ce\u9632',order:'\u6cbb\u5b89',
civil:'\u5185\u653f',military:'\u519b\u4e8b',officer:'\u6b66\u5c06',
civilPanel:'\u5185\u653f\u547d\u4ee4',
militaryPanel:'\u519b\u4e8b\u4e0e\u5916\u4ea4',
officerPanel:'\u6b66\u5c06\u7ba1\u7406',
develop:'\u5f00\u53d1',tax:'\u5f81\u7a0e',recruit:'\u5f81\u5175',hire:'\u62db\u63fd',
noTarget:'\u6682\u65e0\u53ef\u653b\u76ee\u6807',
noTruce:'\u6682\u65e0\u8bae\u548c\u5bf9\u8c61',
truce:'\u8bae\u548c ',
railNote1:'\u654c\u519b\u4f1a\u4e3b\u52a8\u8fdb\u653b\u3002',
railNote2:'\u6218\u679c\u5728\u7ed3\u675f\u672c\u6708\u65f6\u7edf\u4e00\u7ed3\u7b97\u3002',
ownOfficers:'\u9a7b\u57ce\u6b66\u5c06',
reserves:'\u5f85\u4efb\u5b98\u5458',
wanderers:'\u5728\u91ce\u6b66\u5c06',
countsSuffix:' \u540d',
abilityNote:'\u7edf\u7387\u591a\u7528\u4e8e\u6218\u9635\uff0c\u653f\u52a1\u591a\u7528\u4e8e\u5f00\u53d1\u4e0e\u5f81\u7a0e\u3002',
militaryOverview:'\u519b\u60c5\u6982\u89c8',
officerOverview:'\u6b66\u5c06\u603b\u89c8',
cityParams:'\u57ce\u5e02\u53c2\u6570',
noCityOfficer:'\u6682\u65e0\u9a7b\u57ce\u4eba\u7269',
noReserve:'\u6682\u65e0\u5f85\u4efb\u5b98\u5458',
noWanderer:'\u672c\u57ce\u6682\u65e0\u5728\u91ce\u4eba\u7269',
selectedCity:'\u5df2\u9009\u57ce\u6c60',
citySelected:'\u53ef\u5728\u53f3\u4fa7\u4efb\u547d\u5b98\u5458\u3001\u5206\u914d\u804c\u8d23\u5e76\u4e0b\u4ee4\u3002',
advisor:'\u519b\u5e08\u6708\u62a5',
actions:'\u884c\u52a8',
system:'\u7cfb\u7edf',
cityView:'\u57ce\u5185\u89c6\u56fe',
switchCity:'\u70b9\u51fb\u53f3\u4e0b\u89d2\u5c0f\u5730\u56fe\u5207\u6362\u57ce\u6c60',
realm:'\u5929\u4e0b\u5f62\u52bf',
quietTitle:'\u9759\u5019\u519b\u4ee4',
quietBody:'\u8bf7\u9009\u62e9\u57ce\u6c60\u5e76\u4e0b\u4ee4\u3002',
abilityBalanced:'\u80fd\u529b\u5747\u8861',
governStrong:'\u7406\u653f\u5f3a',
leadStrong:'\u7edf\u519b\u5f3a',
plotStrong:'\u7b79\u8c0b\u5f3a',
chargeStrong:'\u51b2\u9635\u5f3a',
appointOfficer:'\u8c03\u5165\u672c\u57ce',
extend:'\u5ef6\u63fd',
assignGovern:'\u7406\u653f',
assignRecruit:'\u7ec3\u5175',
assignDefend:'\u5b88\u5907',
lordFallback:'\u4e00\u65b9\u96c4\u4e3b\uff0c\u6267\u638c\u5f53\u524d\u52bf\u529b\u519b\u653f\u3002',
lordSuffix:'\u541b\u4e3b'
};
function e(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function forceName(state,id){return state.forces[id]?state.forces[id].nameZh:S.none;}
function tip(text){return ' title="'+e(text)+'"';}
function topButtons(appState){return '<button class="toggle" data-view-action="toggle-audio">'+e(appState.audioEnabled?S.soundOn:S.soundOff)+'</button><button class="toggle" data-view-action="toggle-fullscreen">'+e(appState.isFullscreen?S.exitFullscreen:S.enterFullscreen)+'</button>';}
function title(appState){const auto=storageApi.loadMeta('auto');return '<div class="screen"><section class="hero"><div class="hero-card"><h1 class="hero-title">'+e(TEXT.title)+'</h1><p class="hero-subtitle">'+e(TEXT.subtitle)+'</p><p class="hero-note">'+e(TEXT.intro)+'</p><div class="hero-actions"><button data-view-action="new-game">'+e(TEXT.menu.newGame)+'</button><button data-view-action="continue-auto" '+(auto?'':'disabled')+'>'+e(TEXT.menu.continueGame)+'</button>'+topButtons(appState)+'</div>'+(appState.notice?'<div class="notice '+(appState.noticeTone==='bad'?'bad':'')+'">'+e(appState.notice)+'</div>':'')+'</div></section></div>';}
function selectForce(appState){return '<div class="screen"><section class="force-select"><div class="force-select-inner"><div><h1>'+e(TEXT.menu.chooseForce)+'</h1><p>'+e(S.selectForceDesc)+'</p></div><div class="force-grid">'+SCENARIO.forces.map(function(force){return '<div class="force-card"><h3>'+e(force.nameZh)+'</h3><p>'+e(TEXT.forceDescriptions[force.id]||'')+'</p><button data-force-id="'+e(force.id)+'">'+e(TEXT.menu.chooseForce)+'</button></div>';}).join('')+'</div><div class="footer-row"><div class="topbar-actions">'+topButtons(appState)+'<button data-view-action="back-title">'+e(TEXT.menu.back)+'</button></div></div></div></section></div>';}
function mapSvg(state, mode){const cities=Object.values(state.cities),seen={},links=[];cities.forEach(function(city){city.neighbors.forEach(function(id){const k=[city.id,id].sort().join(':');if(seen[k]){return;}seen[k]=true;const n=state.cities[id];if(n){links.push('<line class="link-line" x1="'+city.x+'" y1="'+city.y+'" x2="'+n.x+'" y2="'+n.y+'" />');}});});const terrain=['<path class="historic-land" d="M90 118 C145 78, 232 63, 312 88 C390 112, 470 136, 545 202 C590 240, 620 302, 612 374 C606 434, 560 474, 500 492 C420 517, 316 520, 240 490 C178 465, 132 430, 106 374 C80 316, 72 168, 90 118 Z" />','<path class="historic-border" d="M92 120 C146 81, 230 65, 310 90 C390 114, 470 138, 544 202 C590 239, 619 302, 611 372 C606 433, 560 472, 499 491 C422 515, 317 518, 241 490 C181 468, 131 430, 106 374 C83 321, 73 169, 92 120 Z" />','<path class="river-line" d="M 120 255 C 190 225, 260 205, 320 212 C 400 220, 470 255, 560 360" />','<path class="river-line thin" d="M 210 110 C 235 145, 260 175, 290 210" />'];
const war=(state.lastWarEffects||[]).map(function(effect){if(!effect.cityId||!state.cities[effect.cityId]){return '';}const city=state.cities[effect.cityId];return '<g class="war-effect"><circle cx="'+city.x+'" cy="'+city.y+'" r="32" class="war-ring"></circle><path d="M'+(city.x-11)+' '+(city.y-15)+' L'+(city.x+11)+' '+(city.y+15)+' M'+(city.x+11)+' '+(city.y-15)+' L'+(city.x-11)+' '+(city.y+15)+'" class="war-cross"></path></g>';}).join('');
const marches=(state.pendingAttacks||[]).map(function(item,index){const from=state.cities[item.fromCityId],target=state.cities[item.targetCityId];if(!from||!target){return '';}const mx=(from.x+target.x)/2;const my=(from.y+target.y)/2;return '<g class="march-line-group delay-'+(index%3)+'"><line class="march-line" x1="'+from.x+'" y1="'+from.y+'" x2="'+target.x+'" y2="'+target.y+'" /><circle class="march-dot" cx="'+mx+'" cy="'+my+'" r="5"></circle></g>';}).join('');
const nodes=cities.map(function(city){const owner=state.forces[city.ownerForceId],selected=state.selectedCityId===city.id?'selected':'',player=city.ownerForceId===state.playerForceId?'player':'',flash=state.lastFeedback&&state.lastFeedback.cityId===city.id?'flash':'';const labelDx=city.x>520?-14:14;const anchor=city.x>520?'end':'start';const label=mode==='mini'?'<text class="mini-city-label '+selected+'" x="'+(city.x+labelDx)+'" y="'+(city.y+4)+'" text-anchor="'+anchor+'">'+e(city.nameZh)+'</text>':'<text x="'+city.x+'" y="'+(city.y+30)+'" text-anchor="middle" fill="#2a190f">'+e(city.nameZh)+'</text>';return '<g class="city-node '+selected+' '+player+' '+flash+'" data-city-id="'+e(city.id)+'"><circle cx="'+city.x+'" cy="'+city.y+'" r="'+(mode==='mini'?'12':'18')+'" fill="rgba(255,247,231,0.96)"></circle><circle cx="'+city.x+'" cy="'+city.y+'" r="'+(mode==='mini'?'8':'12')+'" fill="'+e(owner?owner.color:'#999999')+'"></circle>'+label+'</g>';}).join('');
return '<svg class="map-svg '+(mode==='mini'?'mini-map-svg':'')+'" viewBox="60 40 620 500" preserveAspectRatio="xMidYMid meet">'+terrain.join('')+links.join('')+marches+war+nodes+'</svg>';
}
function roleClass(role){return (role||'').indexOf('\u6587')>=0||(role||'').indexOf('\u8c0b')>=0||(role||'').indexOf('\u5e55')>=0||(role||'').indexOf('\u6267\u653f')>=0||(role||'').indexOf('\u8fd1\u81e3')>=0?'civil':((role||'').indexOf('\u5c06')>=0||(role||'').indexOf('\u5b88')>=0?'military':'mixed');}
function portraitPalette(officer,state){const force=officer.forceId&&state.forces[officer.forceId]?state.forces[officer.forceId]:null;const role=roleClass(officer.role);if(role==='civil'){return {bg:'#e8dcc8',robe:'#5a6f84',trim:'#d7d1c8',hat:'#2a2d34',face:'#eac7aa',shadow:'#ba8e70'};}if(role==='military'){return {bg:'#e7d7c5',robe:'#6d4732',trim:'#b98a56',hat:'#3a261b',face:'#e6c1a1',shadow:'#b27d61'};}return {bg:'#eadbc3',robe:(force&&force.color)||'#7b5237',trim:'#d2b06b',hat:'#231a14',face:'#ebc7a8',shadow:'#b78363'};}
function inlinePortrait(officer,state){const c=portraitPalette(officer,state);const beard=(officer.might>=72||officer.leadership>=78)?'<path d="M34 60 C36 68, 44 68, 46 60" fill="none" stroke="#3a2419" stroke-width="2.2" stroke-linecap="round"/>':'';const moustache=officer.intellect>=74?'<path d="M32 56 C34 54, 38 54, 40 56 M40 56 C42 54, 46 54, 48 56" fill="none" stroke="#4a3022" stroke-width="1.6" stroke-linecap="round"/>':'';const crest=roleClass(officer.role)==='civil'?'<path d="M28 22 L52 22 L47 15 L33 15 Z" fill="#d7d1c8"/>':(roleClass(officer.role)==='military'?'<path d="M30 20 L50 20 L46 13 L34 13 Z" fill="'+c.trim+'"/>':'<rect x="36" y="10" width="8" height="10" rx="2" fill="'+c.trim+'"/>');return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96" aria-hidden="true">'+'<rect x="2" y="2" width="92" height="92" rx="14" fill="'+c.bg+'" stroke="rgba(93,63,42,0.28)"/>'+'<ellipse cx="48" cy="92" rx="28" ry="8" fill="rgba(0,0,0,0.08)"/>'+'<path d="M18 90 C22 68, 32 56, 48 56 C64 56, 74 68, 78 90" fill="'+c.robe+'"/>'+'<path d="M37 57 L59 57 L55 90 L41 90 Z" fill="'+c.trim+'" opacity="0.72"/>'+'<path d="M28 40 C28 26, 36 18, 48 18 C60 18, 68 26, 68 40 C68 53, 61 62, 48 62 C35 62, 28 53, 28 40 Z" fill="'+c.face+'"/>'+'<path d="M26 39 C26 24, 36 15, 48 15 C60 15, 70 24, 70 39 L66 36 C64 28, 58 23, 48 23 C38 23, 32 28, 30 36 Z" fill="'+c.hat+'"/>'+'<rect x="24" y="22" width="48" height="6" rx="2" fill="'+c.hat+'"/>'+crest+'<circle cx="40" cy="42" r="2.2" fill="#1f1612"/>'+'<circle cx="56" cy="42" r="2.2" fill="#1f1612"/>'+'<path d="M36 37 C38 35, 41 35, 43 37 M53 37 C55 35, 58 35, 60 37" fill="none" stroke="#3b281d" stroke-width="1.6" stroke-linecap="round"/>'+'<path d="M48 44 L46 52 L49 52" fill="none" stroke="'+c.shadow+'" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>'+'<path d="M41 56 C44 58, 52 58, 55 56" fill="none" stroke="#8a5b49" stroke-width="1.8" stroke-linecap="round"/>'+moustache+beard+'</svg>';}
function avatarMarkup(officer,state){if(officer.avatar&&officer.avatar.indexOf('<svg')>=0){return officer.avatar;}const force=officer.forceId&&state.forces[officer.forceId]?state.forces[officer.forceId]:null;const generated=window.FDTK.makeOfficerAvatar?window.FDTK.makeOfficerAvatar(officer,force):'';if(generated&&generated.indexOf('<svg')>=0){return generated;}return inlinePortrait(officer,state);}
function officerEffect(officer){const parts=[];if(officer.politics>=72){parts.push(S.governStrong);}if(officer.leadership>=72){parts.push(S.leadStrong);}if(officer.intellect>=72){parts.push(S.plotStrong);}if(officer.might>=72){parts.push(S.chargeStrong);}return parts.length?parts.join(' / '):S.abilityBalanced;}
function officerButtons(officer,mode){if(mode==='duty'){return '<div class="officer-actions compact-duty"><button data-game-action="assign-duty" data-officer-id="'+e(officer.id)+'" data-duty="govern">'+S.assignGovern+'</button><button data-game-action="assign-duty" data-officer-id="'+e(officer.id)+'" data-duty="recruit">'+S.assignRecruit+'</button><button data-game-action="assign-duty" data-officer-id="'+e(officer.id)+'" data-duty="defend">'+S.assignDefend+'</button></div>';}if(mode==='appoint'){return '<div class="officer-actions compact-duty"><button data-game-action="appoint-officer" data-officer-id="'+e(officer.id)+'">'+S.appointOfficer+'</button><button data-game-action="assign-duty" data-officer-id="'+e(officer.id)+'" data-duty="hire">'+S.extend+'</button></div>';}return '';} 
function officerCard(officer,mode,state){const bio=officer.bio||'';return '<div class="officer-card compact slim-officer '+roleClass(officer.role)+'"><div class="portrait small"'+tip(bio)+'>'+avatarMarkup(officer,state)+'</div><div class="officer-meta"><div class="officer-head"><strong>'+e(officer.nameZh)+'</strong><div class="badge-row"><span class="badge">'+e(officer.role||S.roleFallback)+'</span></div></div><div class="officer-stats">\u7edf'+officer.leadership+' \u6b66'+officer.might+' \u667a'+officer.intellect+' \u653f'+officer.politics+' \u5fe0'+officer.loyalty+'</div><div class="officer-impact">'+e(officerEffect(officer))+'</div><small>'+e(bio||'')+'</small>'+officerButtons(officer,mode)+'</div></div>';}
function helpDrawer(){return '<details class="help-drawer"><summary>'+S.help+'</summary><div class="help-grid"><div class="help-item">'+S.help1+'</div><div class="help-item">'+S.help2+'</div><div class="help-item">'+S.help3+'</div><div class="help-item">'+S.help4+'</div></div></details>';}
function buildTaxHint(city,action){if(action.enabled){return S.taxHintEnabled+city.taxBurden+'\u3002';}return S.taxHintDisabled+city.population+S.taxHintMid+city.loyalty+S.taxHintEnd+city.taxBurden+'\u3002';}
function buildRecruitHint(city,action){if(action.enabled){return S.recruitHintEnabled+city.conscription+'\u3002';}return S.recruitHintDisabled+city.population+S.recruitHintMid+city.loyalty+S.recruitHintEnd+city.conscription+'\u3002';}
function metric(label,value,info){return '<div class="status-metric"'+tip(info)+'><span>'+e(label)+'</span><strong>'+e(String(value))+'</strong></div>';}
function districtArt(cls){if(cls==='farm'){return '<div class="district-art"><span class="field-row"></span><span class="field-row"></span><span class="field-row"></span></div>';}if(cls==='market'){return '<div class="district-art"><span class="stall-roof"></span><span class="stall-box"></span><span class="stall-box small"></span></div>';}if(cls==='office'){return '<div class="district-art"><span class="hall-roof"></span><span class="hall-body"></span><span class="hall-door"></span></div>';}if(cls==='barracks'){return '<div class="district-art"><span class="spear"></span><span class="spear two"></span><span class="shield"></span></div>';}if(cls==='wall'){return '<div class="district-art"><span class="gate-tower"></span><span class="gate-wall"></span></div>';}return '<div class="district-art"><span class="house-roof"></span><span class="house-body"></span><span class="house-door"></span></div>';}
function districtCard(cls,title,meta,value){return '<div class="district-card '+cls+'">'+districtArt(cls)+'<span class="district-title">'+e(title)+'</span><strong class="district-value">'+e(String(value))+'</strong><small class="district-meta">'+e(meta)+'</small></div>';}
function cityScene(city,ownerName,feedback,advisor){return '<div class="city-scene"><div class="scene-sky"></div><div class="scene-ridge back"></div><div class="scene-ridge mid"></div><div class="scene-ground"></div><div class="scene-wall-ring"></div><div class="scene-yard"></div><div class="scene-road-axis"></div><div class="scene-label-panel"><strong>'+e(city.nameZh)+'</strong><span>'+e(ownerName)+'</span></div><div class="scene-feedback '+e(feedback.tone)+'"><strong>'+e(feedback.title)+'</strong><span>'+e(feedback.body)+'</span></div><div class="scene-advisor"><strong>'+S.advisor+'</strong><span>'+e(advisor.summary)+'</span></div><div class="scene-districts">'+districtCard('farm',S.farm,S.population,city.population||'--')+districtCard('market',S.market,S.development,city.development)+districtCard('office',S.office,S.loyalty,city.loyalty)+districtCard('barracks',S.barracks,S.troops,city.troops)+districtCard('wall',S.gate,S.defense,city.defense)+districtCard('ward',S.ward,S.order,city.order)+'</div></div>';}
function panelTabs(current){const tabs=[['civil',S.civil],['military',S.military],['officer',S.officer]];return '<div class="panel-tabs">'+tabs.map(function(item){return '<button class="panel-tab '+(current===item[0]?'active':'')+'" data-panel-id="'+item[0]+'">'+item[1]+'</button>';}).join('')+'</div>';}
function civilPanel(city,actDevelop,actTax,actRecruit,actHire,taxBurden,conscription){return '<section class="rail-card"><h3>'+S.civilPanel+'</h3><div class="rail-buttons"><button data-game-action="develop" '+(actDevelop.enabled?'':'disabled')+tip(TEXT.help.actions.develop)+'>'+S.develop+'</button><button data-game-action="tax" '+(actTax.enabled?'':'disabled')+tip(buildTaxHint(city,actTax))+'>'+S.tax+'</button><button data-game-action="recruit" '+(actRecruit.enabled?'':'disabled')+tip(buildRecruitHint(city,actRecruit))+'>'+S.recruit+'</button><button data-game-action="hire" '+(actHire.enabled?'':'disabled')+tip(TEXT.help.actions.hire)+'>'+S.hire+'</button></div><div class="rail-notes"><div class="help-item">\u7a0e\u8d1f\uff1a'+e(String(taxBurden))+'</div><div class="help-item">\u5175\u5f79\uff1a'+e(String(conscription))+'</div></div></section>';}
function militaryPanel(actAttack,actTruce){return '<section class="rail-card"><h3>'+S.militaryPanel+'</h3><div class="rail-buttons target-buttons">'+(actAttack.options.length?actAttack.options.map(function(opt){return '<button data-game-action="attack" data-target-city-id="'+e(opt.cityId)+'" '+(actAttack.enabled?'':'disabled')+tip(TEXT.help.actions.attack)+'>'+e(opt.label)+'</button>';}).join(''):'<button disabled>'+S.noTarget+'</button>')+(actTruce.options.length?actTruce.options.map(function(opt){return '<button data-game-action="truce" data-target-force-id="'+e(opt.forceId)+'" '+(actTruce.enabled?'':'disabled')+tip(TEXT.help.actions.truce)+'>'+S.truce+e(opt.label)+'</button>';}).join(''):'<button disabled>'+S.noTruce+'</button>')+'</div><div class="rail-notes"><div class="help-item">'+S.railNote1+'</div><div class="help-item">'+S.railNote2+'</div></div></section>';}
function officerPanel(cityView){return '<section class="rail-card"><h3>'+S.officerPanel+'</h3><div class="help-grid"><div class="help-item">'+S.ownOfficers+' '+cityView.ownOfficers.length+S.countsSuffix+'</div><div class="help-item">'+S.reserves+' '+cityView.reserves.length+S.countsSuffix+'</div><div class="help-item">'+S.wanderers+' '+((cityView.wanderers||[]).length)+S.countsSuffix+'</div><div class="help-item">'+S.abilityNote+'</div></div></section>';}
function officerSection(title,list,mode,state,emptyText){return '<section class="officer-group"><div class="officer-group-title"><strong>'+e(title)+'</strong><span>'+list.length+S.countsSuffix+'</span></div>'+(list.length?'<div class="roster-grid">'+list.map(function(o){return officerCard(o,mode,state);}).join('')+'</div>':'<div class="city-officer">'+e(emptyText)+'</div>')+'</section>';}
function centerInfoPanel(current,state,city,cityView,feedback,advisor){if(current==='military'){return '<section class="info-card"><h3>'+S.militaryOverview+'</h3><div class="detail-grid compact-grid"><div class="detail-row">'+S.order+' '+cityView.frontierPressure+'</div><div class="detail-row">'+S.troops+' '+city.troops+'</div><div class="detail-row">'+S.defense+' '+city.defense+'</div><div class="detail-row">'+S.loyalty+' '+city.loyalty+'</div></div><div class="log-list compact-log-list top-gap">'+state.logs.slice(0,5).map(function(entry){return '<div class="log-entry"><small>'+e(entry.time)+'</small>'+e(entry.text)+'</div>';}).join('')+'</div></section>';}if(current==='officer'){return '<section class="info-card officer-roster-panel"><h3>'+S.officerOverview+'</h3><div class="roster-sections">'+officerSection(S.ownOfficers,cityView.ownOfficers,'duty',state,S.noCityOfficer)+officerSection(S.reserves,cityView.reserves,'appoint',state,S.noReserve)+officerSection(S.wanderers,cityView.wanderers||[],'wanderer',state,S.noWanderer)+'</div></section>';}return '<section class="info-card"><h3>'+S.cityParams+'</h3><div class="detail-grid compact-grid"><div class="detail-row"'+tip('\u5175\u529b\uff1a\u57ce\u5e02\u5b88\u519b\u4e0e\u51fa\u5f81\u80fd\u529b\u3002')+'>'+S.troops+' '+city.troops+'</div><div class="detail-row"'+tip('\u4eba\u53e3\u51b3\u5b9a\u57ce\u5e02\u6062\u590d\u80fd\u529b\u4e0e\u62bd\u53d6\u7a7a\u95f4\uff0c\u8fc7\u4f4e\u65f6\u4e0d\u5b9c\u518d\u5f3a\u5f81\u3002')+'>'+S.population+' '+city.population+'</div><div class="detail-row"'+tip('\u7a0e\u8d1f\u8d8a\u9ad8\uff0c\u5f81\u7a0e\u526f\u4f5c\u7528\u8d8a\u5f3a\uff0c\u6708\u521d\u4f1a\u9010\u6b65\u56de\u843d\u3002')+'>'+('\u7a0e\u8d1f')+' '+city.taxBurden+'</div><div class="detail-row"'+tip('\u5175\u5f79\u8d8a\u9ad8\uff0c\u5f81\u5175\u526f\u4f5c\u7528\u8d8a\u5f3a\uff0c\u6708\u521d\u4f1a\u9010\u6b65\u56de\u843d\u3002')+'>'+('\u5175\u5f79')+' '+city.conscription+'</div><div class="detail-row"'+tip(TEXT.help.stats.order)+'>'+S.order+' '+city.order+'</div><div class="detail-row"'+tip(TEXT.help.stats.defense)+'>'+S.defense+' '+city.defense+'</div><div class="detail-row"'+tip(TEXT.help.stats.loyalty)+'>'+S.loyalty+' '+city.loyalty+'</div><div class="detail-row"'+tip(TEXT.help.stats.development)+'>'+S.development+' '+city.development+'</div></div><div class="help-grid top-gap"><div class="help-item">'+e(feedback.title)+'\uff1a'+e(feedback.body)+'</div><div class="help-item">'+e(advisor.summary)+'</div></div></section>';}
function game(appState){const state=appState.game,overview=gameApi.getForceOverview(state,state.playerForceId),cityView=gameApi.getCityView(state,state.selectedCityId),actions=gameApi.getAvailableActions(state),feedback=state.lastFeedback||{title:S.quietTitle,body:S.quietBody,tone:'normal'},advisor=state.advisorReport||{title:S.advisor,summary:'',lines:[]};function find(id){return actions.find(function(a){return a.id===id;})||{enabled:false,options:[]};}
const actAttack=find('attack'),actTruce=find('truce'),actDevelop=find('develop'),actTax=find('tax'),actRecruit=find('recruit'),actHire=find('hire');
const city=cityView.city;const playerForce=state.forces[state.playerForceId];const rulerRaw=state.officers[playerForce.rulerOfficerId]||gameApi.getForceOfficers(state,state.playerForceId)[0]||cityView.ownOfficers[0]||null;const ruler=rulerRaw?Object.assign({},rulerRaw,{avatar:avatarMarkup(rulerRaw,state),bio:rulerRaw.bio||S.lordFallback}):null;const advisorLines=advisor.lines.slice(0,3);const current=appState.currentPanel||'civil';
let railContent='';if(current==='civil'){railContent=civilPanel(city,actDevelop,actTax,actRecruit,actHire,city.taxBurden||0,city.conscription||0);}else if(current==='military'){railContent=militaryPanel(actAttack,actTruce);}else{railContent=officerPanel(cityView);} 
return '<div class="screen game-shell civic-shell"><div class="civic-topbar"><div class="date-banner">'+e(fmt.monthLabel(state.year,state.month))+' \u00b7 '+e(city.nameZh)+S.civil+'</div><div class="topbar-actions">'+topButtons(appState)+'<button data-save-slot="1">\u5b581</button><button data-save-slot="2">\u5b582</button><button data-save-slot="3">\u5b583</button><button data-view-action="back-title">'+e(TEXT.menu.back)+'</button></div></div><div class="civic-status-row"><section class="status-panel lord-panel">'+(ruler?'<div class="ruler-wrap"><div class="portrait hero-portrait"'+tip(ruler.bio)+'>'+ruler.avatar+'</div><div><h2>'+e(ruler.nameZh)+'</h2><div class="mini-note">'+e(playerForce.nameZh)+S.lordSuffix+'</div><div class="status-inline">\u7edf'+ruler.leadership+' \u6b66'+ruler.might+' \u667a'+ruler.intellect+' \u653f'+ruler.politics+' \u5fe0'+ruler.loyalty+'</div><p class="mini-bio">'+e(ruler.bio||'')+'</p></div></div>':'<h2>'+e(playerForce.nameZh)+'</h2>')+'</section><section class="status-panel overview-panel"><h3>'+e('\u52bf\u529b\u603b\u89c8')+'</h3><div class="status-grid">'+metric(TEXT.labels.gold,playerForce.gold,TEXT.help.stats.gold)+metric(TEXT.labels.food,playerForce.food,TEXT.help.stats.food)+metric(TEXT.labels.troops,overview.troops,'')+metric(TEXT.labels.cities,overview.cities.length,'')+metric(TEXT.labels.officersCount,overview.officers.length,'')+metric(S.actions,fmt.actionUsage(state),'')+'</div></section><section class="status-panel city-panel"><h3>'+e(city.nameZh)+'</h3><div class="status-grid compact">'+metric(TEXT.labels.order,city.order,TEXT.help.stats.order)+metric(TEXT.labels.defense,city.defense,TEXT.help.stats.defense)+metric(TEXT.labels.loyalty,city.loyalty,TEXT.help.stats.loyalty)+metric(TEXT.labels.development,city.development,TEXT.help.stats.development)+metric(S.population,city.population,'')+metric('\u524d\u7ebf',cityView.frontierPressure,'')+'</div></section></div><div class="civic-main"><aside class="command-rail">'+panelTabs(current)+railContent+'<section class="rail-card slim-bottom-card"><h3>'+S.system+'</h3>'+helpDrawer()+'<button class="primary-endturn" data-game-action="endTurn">'+e(TEXT.game.endTurn)+'</button></section></aside><section class="city-stage-card"><div class="stage-header"><div><h3>'+e(city.nameZh)+S.cityView+'</h3><small>'+S.switchCity+'</small></div><span class="badge">'+e(forceName(state,city.ownerForceId))+'</span></div><div class="stage-main">'+cityScene(city,forceName(state,city.ownerForceId),feedback,advisor)+'<div class="mini-map-panel"><div class="mini-map-title">'+S.realm+'</div>'+mapSvg(state,'mini')+'</div></div><div class="advisor-strip">'+advisorLines.map(function(line){return '<div class="advisor-note">'+e(line)+'</div>';}).join('')+'</div></section><aside class="info-rail">'+centerInfoPanel(current,state,city,cityView,feedback,advisor)+'</aside></div></div>';}
function gameOver(appState){const result=appState.game&&appState.game.gameOver?appState.game.gameOver:{title:'',body:''};return '<div class="screen"><section class="game-over"><div class="game-over-card"><h2>'+e(result.title)+'</h2><p>'+e(result.body)+'</p><div class="hero-actions"><button data-view-action="new-game">'+e(TEXT.menu.newGame)+'</button><button data-view-action="continue-auto">'+e(TEXT.menu.continueGame)+'</button>'+topButtons(appState)+'<button data-view-action="back-title">'+e(TEXT.menu.back)+'</button></div></div></section></div>';}
function bind(root,handlers){root.querySelectorAll('[data-view-action]').forEach(function(button){button.addEventListener('click',function(){const action=button.getAttribute('data-view-action');const slotId=button.getAttribute('data-slot-id');if(action==='new-game')handlers.newGame();if(action==='continue-auto')handlers.continueAuto();if(action==='back-title')handlers.backTitle();if(action==='load-slot')handlers.loadSlot(slotId);if(action==='toggle-audio')handlers.toggleAudio();if(action==='toggle-fullscreen')handlers.toggleFullscreen();});});root.querySelectorAll('[data-panel-id]').forEach(function(button){button.addEventListener('click',function(){handlers.setPanel(button.getAttribute('data-panel-id'));});});root.querySelectorAll('[data-force-id]').forEach(function(button){button.addEventListener('click',function(){handlers.chooseForce(button.getAttribute('data-force-id'));});});root.querySelectorAll('[data-city-id]').forEach(function(node){node.addEventListener('click',function(){handlers.selectCity(node.getAttribute('data-city-id'));});});root.querySelectorAll('[data-game-action]').forEach(function(button){button.addEventListener('click',function(){handlers.gameAction({type:button.getAttribute('data-game-action'),targetCityId:button.getAttribute('data-target-city-id'),targetForceId:button.getAttribute('data-target-force-id'),officerId:button.getAttribute('data-officer-id'),duty:button.getAttribute('data-duty')});});});root.querySelectorAll('[data-save-slot]').forEach(function(button){button.addEventListener('click',function(){handlers.saveSlot(button.getAttribute('data-save-slot'));});});}
window.FDTK.ui={renderApp:function(root,appState,handlers){if(appState.screen==='title'){root.innerHTML=title(appState);bind(root,handlers);return;}if(appState.screen==='select-force'){root.innerHTML=selectForce(appState);bind(root,handlers);return;}if(appState.screen==='game-over'){root.innerHTML=gameOver(appState);bind(root,handlers);return;}root.innerHTML=game(appState);bind(root,handlers);}};
})();


