(function(){
const old=window.FDTK.game;const TEXT=window.FDTK.TEXT;const fmt=window.FDTK.formatters;
function clone(v){return JSON.parse(JSON.stringify(v));}
function flagsForCities(cities){const out={};Object.keys(cities).forEach(function(id){out[id]={civilUsed:false,strategicUsed:false};});return out;}
function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
function dutyLabel(d){return TEXT.duties[d]||TEXT.duties.idle;}
function inferDuty(o){if(o.role.indexOf('文')>=0||o.role.indexOf('谋')>=0||o.role.indexOf('政')>=0){return 'govern';}if(o.role.indexOf('守')>=0){return 'defend';}if(o.role.indexOf('将')>=0||o.role.indexOf('宿')>=0){return 'recruit';}return 'idle';}
function ensureState(state){if(!state){return state;}Object.values(state.officers||{}).forEach(function(o){if(!o.duty){o.duty=inferDuty(o);}});if(!state.cityMonthFlags){state.cityMonthFlags=flagsForCities(state.cities||{});if(state.selectedCityId&&state.monthFlags){state.cityMonthFlags[state.selectedCityId]=clone(state.monthFlags);}}Object.keys(state.cities||{}).forEach(function(id){if(!state.cityMonthFlags[id]){state.cityMonthFlags[id]={civilUsed:false,strategicUsed:false};}});if(!state.selectedCityId){const first=Object.values(state.cities||{})[0];state.selectedCityId=first?first.id:null;}state.monthFlags=clone(state.cityMonthFlags[state.selectedCityId]||{civilUsed:false,strategicUsed:false});if(!state.lastFeedback){state.lastFeedback={title:'静候军令',body:'请选择城池并查看右侧说明。',tone:'normal',cityId:state.selectedCityId||null};}if(!state.advisorReport){state.advisorReport=makeAdvisorReport(state);}return state;}
function setFeedback(state,title,body,tone,cityId){state.lastFeedback={title:title,body:body,tone:tone||'normal',cityId:cityId||null,tick:(state.lastFeedback&&state.lastFeedback.tick?state.lastFeedback.tick:0)+1};}
function getForceCities(state,forceId){return Object.values(state.cities).filter(function(c){return c.ownerForceId===forceId;});}
function getForceOfficers(state,forceId){return Object.values(state.officers).filter(function(o){return o.forceId===forceId;});}
function getCityOfficers(state,cityId,forceId){return Object.values(state.officers).filter(function(o){return o.cityId===cityId&&(forceId?o.forceId===forceId:!!o.forceId);});}
function getReserveOfficers(state,forceId){return getForceOfficers(state,forceId).filter(function(o){return !o.assigned;});}
function getFreeOfficersInCity(state,cityId){return Object.values(state.officers).filter(function(o){return !o.forceId&&o.cityId===cityId;});}
function best(list,key){return list.length?list.slice().sort(function(a,b){return (b[key]||0)-(a[key]||0);})[0]:null;}
function makeAdvisorReport(state){const cities=getForceCities(state,state.playerForceId);const enemyCount=Object.values(state.forces).filter(function(f){return f.alive&&f.id!==state.playerForceId;}).length;const weak=cities.filter(function(city){return city.neighbors.some(function(n){const other=state.cities[n];return other&&other.ownerForceId!==state.playerForceId&&other.troops>city.troops;});}).sort(function(a,b){return a.troops-b.troops;})[0];const rich=cities.slice().sort(function(a,b){return b.development-a.development;})[0];const reserves=getReserveOfficers(state,state.playerForceId).length;const lines=[];if(weak){lines.push('前线以'+weak.nameZh+'最为吃紧，宜优先练兵或守备。');}if(rich){lines.push(rich.nameZh+'开发较高，可继续作为财粮重镇。');}if(reserves){lines.push('仍有'+reserves+'名待任官员，可补往要地。');}if(!lines.length){lines.push('诸城暂稳，可择机进取。');}return{title:'军师月报',summary:'今月尚有敌对势力 '+enemyCount+' 家，我军共据 '+cities.length+' 城。',lines:lines};}
function syncSelectedFlags(state){state.monthFlags=clone(state.cityMonthFlags[state.selectedCityId]||{civilUsed:false,strategicUsed:false});}
function saveSelectedFlags(state){state.cityMonthFlags[state.selectedCityId]=clone(state.monthFlags||{civilUsed:false,strategicUsed:false});}
function createNewGame(forceId){const state=ensureState(old.createNewGame(forceId));state.cityMonthFlags=flagsForCities(state.cities);syncSelectedFlags(state);state.advisorReport=makeAdvisorReport(state);setFeedback(state,'新局已开',state.advisorReport.summary+' '+state.advisorReport.lines.join(' '),'event',state.selectedCityId);return state;}
function getAvailableActions(input){const state=ensureState(clone(input));syncSelectedFlags(state);const actions=old.getAvailableActions(state);const map={};actions.forEach(function(a){map[a.id]=a;});if(!map.appoint){map.appoint={id:'appoint',label:TEXT.actions.appoint,enabled:getReserveOfficers(state,state.playerForceId).length>0,options:[]};}return Object.keys(map).map(function(k){return map[k];});}
function officerBio(o){const stats=[['统率',o.leadership],['武勇',o.might],['智略',o.intellect],['政务',o.politics]].sort(function(a,b){return b[1]-a[1];});return o.role+'。'+stats[0][0]+'见长，当前职责为'+dutyLabel(o.duty)+'。忠诚 '+o.loyalty+'。';}
function getForceOverview(input,forceId){const state=ensureState(clone(input));const base=old.getForceOverview(state,forceId);const cities=getForceCities(state,forceId);base.availableCivil=cities.filter(function(c){return !state.cityMonthFlags[c.id].civilUsed;}).length;base.availableStrategic=cities.filter(function(c){return !state.cityMonthFlags[c.id].strategicUsed;}).length;return base;}
function getCityView(input,cityId){const state=ensureState(clone(input));const base=old.getCityView(state,cityId);base.ownOfficers=getCityOfficers(state,cityId,state.playerForceId).map(function(o){o.bio=officerBio(o);return o;});base.reserves=getReserveOfficers(state,state.playerForceId).map(function(o){o.bio=officerBio(o);return o;});base.wanderers=getFreeOfficersInCity(state,cityId).map(function(o){o.bio=officerBio(o);return o;});base.cityFlags=state.cityMonthFlags[cityId]||{civilUsed:false,strategicUsed:false};return base;}
function appointOfficer(state,officerId){const city=state.cities[state.selectedCityId];const officer=state.officers[officerId];if(!city||city.ownerForceId!==state.playerForceId||!officer||officer.forceId!==state.playerForceId||officer.assigned||state.monthFlags.strategicUsed){return state;}officer.cityId=city.id;officer.assigned=true;officer.loyalty=clamp(officer.loyalty+6,30,100);if(officer.duty==='idle'){officer.duty=inferDuty(officer);}state.monthFlags.strategicUsed=true;saveSelectedFlags(state);setFeedback(state,'任命完成',officer.nameZh+'已调赴'+city.nameZh+'，职责为'+dutyLabel(officer.duty)+'。','normal',city.id);state.logs.unshift({id:'appoint-'+Date.now(),time:fmt.monthLabel(state.year,state.month),text:officer.nameZh+'赴'+city.nameZh+'任事。',tone:'normal'});return state;}
function assignDuty(state,officerId,duty){const city=state.cities[state.selectedCityId];const officer=state.officers[officerId];if(!city||!officer||officer.forceId!==state.playerForceId||officer.cityId!==city.id){return state;}officer.duty=duty;setFeedback(state,'职责已定',officer.nameZh+'现负责'+dutyLabel(duty)+'。','normal',city.id);state.logs.unshift({id:'duty-'+Date.now(),time:fmt.monthLabel(state.year,state.month),text:officer.nameZh+'在'+city.nameZh+'改任'+dutyLabel(duty)+'。',tone:'normal'});return state;}
function syncAfterOld(next){ensureState(next);saveSelectedFlags(next);return next;}
function applyAction(input,action){let state=ensureState(clone(input));if(action.type==='selectCity'){state.selectedCityId=action.cityId;syncSelectedFlags(state);setFeedback(state,'已选中城池',state.cities[action.cityId].nameZh+'已进入查看状态。可在右侧任命官员、分配职责并下令。','normal',action.cityId);return state;}syncSelectedFlags(state);if(action.type==='appoint-officer'){return appointOfficer(state,action.officerId);}if(action.type==='assign-duty'){return assignDuty(state,action.officerId,action.duty);}if(action.type==='endTurn'){const next=ensureState(old.applyAction(state,action));next.cityMonthFlags=flagsForCities(next.cities);syncSelectedFlags(next);next.advisorReport=makeAdvisorReport(next);setFeedback(next,next.advisorReport.title,next.advisorReport.summary+' '+next.advisorReport.lines.join(' '),'event',next.selectedCityId);return next;}const next=ensureState(old.applyAction(state,action));next.cityMonthFlags=state.cityMonthFlags;syncAfterOld(next);if(action.type==='develop'){setFeedback(next,'开发完成',next.cities[next.selectedCityId].nameZh+'已推进开发，开发度与秩序有所改善。','normal',next.selectedCityId);}if(action.type==='tax'){setFeedback(next,'征税完成',next.cities[next.selectedCityId].nameZh+'立即得金，但地方负担上升。','normal',next.selectedCityId);}if(action.type==='recruit'){setFeedback(next,'征兵完成',next.cities[next.selectedCityId].nameZh+'兵力已经上升。','normal',next.selectedCityId);}if(action.type==='hire'){if(next.logs[0]&&next.logs[0].text.indexOf('未果')>=0){setFeedback(next,'招揽未果','此次游说未能立刻奏效。','bad',next.selectedCityId);}else{setFeedback(next,'招揽进行','已派人延揽当地游士。','normal',next.selectedCityId);}}if(action.type==='attack'){setFeedback(next,'军令已下','本城出兵已定，战果将在月底统一结算。','battle',next.selectedCityId);}if(action.type==='truce'){setFeedback(next,'议和达成','已与邻国暂定停战。','normal',next.selectedCityId);}return next;}
window.FDTK.game={createNewGame:createNewGame,getAvailableActions:getAvailableActions,applyAction:applyAction,runAiPhase:old.runAiPhase,resolveBattles:old.resolveBattles,advanceMonth:old.advanceMonth,getForceOverview:getForceOverview,getCityView:getCityView,getForceCities:getForceCities,getForceOfficers:getForceOfficers};
})();
